### ISSUE TITLE
Unable to replicate pattern 

### ISSUE THREAD

**Issue by Grant-Steinfeld** [yigitpolat/Hyperledger-Fabric-for-Trusted-IoT#5]
Both @johnwalicki and myself were able to successfully run this pattern on / around
9/8/2019 on a **single** worker node Kubernetes cluster on our shared developer advocate account [ 1323471 - IBM ] 

Cluster ID: blq8n4id0vruks6debk0
Master status: Ready
Version: Kubernetes] 1.14.8_1536
Zones: dal10
Creator: Grant.Steinfeld@ibm.com
Created: 9/8/2019, 1:04 AM
Infrastructure user: 1323471_ptitzler@us.ibm.com
Ingress subdomain: --
Resource group: default

it installed and ran perfectly on 9/8/2019 
it is running fine to this day

subsequent installs on free k8s clusters provisioned by @awesome(JJ) or on a new k8s cluster the pattern fails on the `join channel` step

Here is my new cluster on our shared developer advocate account [ 1323471 - IBM ]  it's not installing on working on:

Cluster ID: bn1j7vnd0s0ikcralfbg
Master status: Ready
Version: [Kubernetes] 1.14.8_1536
Zones: dal10
Creator: Grant.Steinfeld@ibm.com
Created: 11/6/2019, 4:00 PM
Infrastructure user: 1323471_ptitzler@us.ibm.com

I attached the error I am getting: 
[TrustedIoT_install_error.txt](https://github.com/yigitpolat/Hyperledger-Fabric-for-Trusted-IoT/files/3849020/TrustedIoT_install_error.txt)

**Comment by yigitpolat** [comment]
hyperledger/fabric-couchdb image version has not been specified, so Kubernetes was using latest tag while pulling the image from dockerhub and reasoning version incompatibility with hyperledger/fabric-peer.

Image tag has been assigned as hyperledger/fabric-couchdb:0.4.14 and bug fixed.

Thanks !
